# Candace Savonen Aug 2021
# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  - files:
      # OTTR workflows
      - source: .github/workflows/check-url.yml
        dest: .github/workflows/check-url.yml
      - source: .github/workflows/delete-preview.yml
        dest: .github/workflows/delete-preview.yml
      - source: .github/workflows/pull_request.yml
        dest: .github/workflows/pull_request.yml
      - source: .github/workflows/render-all.yml
        dest: .github/workflows/render-all.yml
      - source: .github/workflows/transfer-rendered-files.yml
        dest: .github/workflows/transfer-rendered-files.yml
      # - source: .github/ISSUE_TEMPLATE/course-problem-report.md
      #   dest: .github/ISSUE_TEMPLATE/course-problem-report.md
      # - source: .github/ISSUE_TEMPLATE/course-content-add.md
      #   dest: .github/ISSUE_TEMPLATE/course-content-add.md
      # - source: .github/ISSUE_TEMPLATE/url-error.md
      #   dest: .github/ISSUE_TEMPLATE/url-error.md
      # OTTR style
      - source: assets/style.css
        dest: assets/style.css
      - source: assets/box_images/
        dest: assets/box_images/
      - source: assets/toc_close.css
        dest: assets/toc_close.css
      # C-MOOR content
      - source: about_c-moor.Rmd
        dest: about_c-moor.Rmd
      # C-MOOR style
      - source: _output.yml
        dest: _output.yml
      - source: assets/C-MOOR_Template/
        dest: assets/C-MOOR_Template/
        deleteOrphaned: true
  # Repositories to receive changes
    repos: |
      C-MOOR/module-model-org-db
      C-MOOR/miniCURE-RNA-seq
