```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

# Introduction

## Welcome to Your Genomics Adventure

[Slides: Welcome to Your Genomics Adventure!](https://docs.google.com/presentation/d/18hYo8xrYkyq3rG7RUy3n3-jWFK_JPs5NNW3HmM9HUeQ/edit?usp=sharing)

## Activity - Create Accounts

### Purpose

Over the course of this semester, we will use the following online platforms:
- [C-MOOR Academy Discussion Forum](https://help.c-moor.org) – Join the community to get help and share your findings
- [Google Docs](https://workspace.google.com/products/docs) – Collaborate on assignments and scientific posters
- [Galaxy](https://usegalaxy.org) – Analyze data with >10,000 tools using a graphical user interface
- [SciServer](https://sciserver.org) – Access virtual machines preinstalled with RStudio, Bioconductor, and more

### Activity

*Estimated time: 30 min*

#### Instructions

Create accounts on the following online platforms:

1. C-MOOR Academy Discussion Forum – [https://help.c-moor.org](https://help.c-moor.org)
- Submit your username using [this form](https://docs.google.com/forms/d/e/1FAIpQLSctd0jPax7Ww9b9XGbzY0PTwmPgm6VQICmsOhVTl6OCDx18Hw/viewform)
2. Google Docs – [https://docs.google.com](https://docs.google.com)
- Test by opening [tax-data-gut.tsv](https://drive.google.com/file/d/1vL6adVIrqxpONbae8rUsneK3tbdCpmR-) with Google Sheets
3. Galaxy – [https://usegalaxy.org](https://usegalaxy.org)
4. SciServer – [https://sciserver.org](https://sciserver.org)

#### Questions

Fill out your username and insert a screenshot of that username in the boxes below.

| 1. C-MOOR Academy Discussion Forum. |
|:-|
| <Username: insert screenshot> |

<br>

| 2. Google Docs.|
|:-|
| <Username: insert screenshot> |

<br>

| 3. Galaxy.|
|:-|
| <Username: insert screenshot> |

<br>

| 4. SciServer.|
|:-|
| <Username: insert screenshot> |

<br>

#### Grading Criteria

- Download as Microsoft Word (.docx) and upload on Canvas

#### Footnotes

**Resources**

- Google doc

**Contributions and Affiliations**

- Frederick Tan, Johns Hopkins University

Last Revised: January 2025


## The Scientic Process 

[Slides: The Scientic Process](https://docs.google.com/presentation/d/1VQE-rXASXIdf8rWLP5UTcrAhM_DcznARVigPTHTfw8M/edit?usp=sharing)

## Homework - Post Introductions

### Purpose

The purpose of this assignment is to learn how to post to the C-MOOR Academy Discussion Forum.  This forum will be the primary place for students, their instructors, and experts to communicate about the student’s research project, professional development opportunities, and more.

### Learning Objectives

1. Learn how to post to a discourse community.
1. Examine the differences between private and public discourse categories. 

### Introduction

Before beginning this assignment, you should have already made an account on the C-MOOR Academy Discussion Forum and been added to the course Category by your instructor.  Within the C-MOOR community, you will find Categories, which can be either private or public. In this course we will use both.  In our private category, students can talk to each other and their instructor and their conversations will not be publicly available.  In the public category, students' posts will be visible on the web.  The value of public discourse communities is that you might get responses by experts that you do not know.
In this assignment, students will post to both a public and private Category within the Community.

### Activity 1 - Create a Topic in a Private Category

*Estimated time: 20 min*

#### Instructions

1. Visit the C-MOOR Academy Discussion Forum (help.c-moor.org) and log in.  
2. It is a good idea to bookmark this page so that you can easily access it throughout the course.
3. Read through the categories in the C-MOOR Academy Discussion Forum. Notice that some categories (at least one) have a lock next to them. This is a Private category, only visible to you, your classmates and your instructor.  If you cannot see your course’s private category when you log in, email your instructor so that they can add you.
4. Click on the private category that belongs to your class: Spring 2025. In this private channel, we will add a “New Topic” in which you can introduce yourself to the class.
5. This first post will be an introduction to your class, including a bit about you and a photo.

**a. Tell your group about yourself. Answer the following questions.**
  1. What is your name?
  2. Why did you decide to take this class? What are you excited to learn about this semester?
  3. Tell us one thing you like to do outside of school and work. 

**b. Include a photo:**
  1. Selfie: if you would like, post a photo of yourself.
  2. Unselfie: or post a photo of something else. Maybe something that you feel represents your life right now, or a picture of something you love. A pet maybe. Just make sure it tells us something about you.

6. Play around with the platform to personalize your post. As you can see in the discourse topic, you can add emojis, upload images, embed content, etc. These features appear in plain text as you’re typing, but you can see a preview of your post on the right.  For your first few posts you may see a Welcome Box on the right instead, you can close this to see the preview. Once you have posted a few times, the Welcome Box will stop appearing.
7. When you are done, click “Create Topic” and it will post for the class to see.
8. If other students have posted their introductions, read them and leave a couple replies. This is a discussion platform after all!

#### Resources

- [C-MOOR Academy Discussion Forum](https://help.c-moor.org)
- [How to add a bookmark in Chrome](https://support.google.com/chrome/answer/188842?co=GENIE.Platform%3DDesktop&hl=en)
- [Discourse New User Guide](https://meta.discourse.org/t/discourse-new-user-guide/96331) 


### Activity 2 - Reply to a Topic in a Public Category

*Estimated time: 10 min*

#### Instructions

1. Navigate back to the C-MOOR Academy Discussion Forum front page. 
1. Click on the “Breakroom” Category. This is an informal category where we can chat about non-science related topics.
1. Look for a topic called “Enduring a Snow Storm” Click on the topic.
1. Read the topic and then click “Reply”.
1. The same box will pop up as you used to to post a topic earlier.
1. Write a reply to the topic.
1. When you are finished click “Reply” to post.

#### Resources

- [C-MOOR Academy Discussion Forum](https://help.c-moor.org)
- [Discourse New User Guide](https://meta.discourse.org/t/discourse-new-user-guide/96331)
   
#### Grading Criteria

- Submit URL to your Private Category Topic on Canvas

#### Footnotes

**Contributions and Affiliations**

- Katherine Cox, Johns Hopkins University
- Valeriya Gaysinskaya, Johns Hopkins University
- Frederick Tan, Johns Hopkins University
- Stephanie Coffman, Clovis Community College

Last Revised: January 2025

