# 2.1 Pre-lab: Scientific Literature

## 2.1.1 Purpose, Learning Objectives and Introduction

### 2.1.1-1 Purpose

Obtain a high level overview of metagenomics by reading
R.D. Sleator, C. Shortall, and C. Hill.  Metagenomics.  Letters in Applied Microbiology. 2008 Nov;47(5):361-6. [(pubmed.gov/19146522)](http://pubmed.gov/19146522)

### 2.1.1-2 Learning Objectives

- Read a review paper that summarizes the field of metagenomics.
- Broadly understand the scope of the review and the gaps in the field. 

### 2.1.1-3 Introduction

The vast majority of all micro-organisms on Earch remain uncultured [(K.G. Lloyd et al, 2019)](https://journals.asm.org/doi/10.1128/msystems.00055-18). Additionally, in complex environments like soil and water, most micro-organisms remain unidentified [(M. Delgado-Baquerizo, 2019)](https://doi.org/10.1038/s41396-019-0405-0). The field of metagenomics is a culture-independend approach which aims to remedy these gaps in knowledge [(J. Handelsman, 2004)](https://pubmed.ncbi.nlm.nih.gov/15590779/). Metagenomics is the study of genomic (sequencing) data obtained directly from environmental (and other, e.g. clinical) samples and provides new meaningful information on the diversity and function of microorganisms.


## 2.1.2 Activity

*Estimated time: 50 min*

### 2.1.2-1 Instructions

Read the review paper “Metagenomics” by Sleator, Shortall, and Hill, 2008 Lett Appl Microbiol and answer the following questions.

### 2.1.2-2 Questions

1. What is one thing you learned or find interesting in the paper?

2. Define a term that is new to you (e.g. metagenome, microbiome, 16S rRNA).

3. Ask a question about the review paper.

### 2.1.2-3 Grading Criteria

Download as Microsoft Word (.docx) and upload on Canvas


## 2.1.3 Footnotes

### 2.1.3-1 Resources

[Google Doc](https://docs.google.com/document/d/1-ruTySaAnSE-_5d6_LTdre4UmmUAx6TxMrTYBW-f3jQ/edit?usp=sharing)

### 2.1.3-2 Contributions and Affiliations

- Valeriya Gaysinskaya, Johns Hopkins University
- Frederick Tan, Johns Hopkins University


