# (PART\*) COMMUNITY ANALYSIS AND FEEDBACK {-}


# Scientific Communication

## Lecture: Scientific Posters

```{r, echo=FALSE, fig.alt=''}
ottrpal::include_slide("https://docs.google.com/presentation/d/1-orSi8DpN22hMt9-6p_rHZnte1YXXLe-a132HDSyd0U/edit?slide=id.g35f391192_00#slide=id.g35f391192_00")
```

[Slides: Finding AMRs](https://docs.google.com/presentation/d/1-orSi8DpN22hMt9-6p_rHZnte1YXXLe-a132HDSyd0U/edit?usp=sharing)

## Activity: Scientific Posters

## Activity

*Estimated time: 50 min*

#### Instructions

1. Review “Presentations Guidelines for Posters”.

- [https://ur.umbc.edu/urcad/resources/posters-guidelines](https://ur.umbc.edu/urcad/resources/posters-guidelines)

2. Skim three posters from among the following (must be Biology if from UMBC Posters)

  a. C-MOOR Posters – [https://help.c-moor.org/c/look-at-this/8](https://help.c-moor.org/c/look-at-this/8)

  b. UMBC Posters – [https://ur.umbc.edu/poster-presentation-examples](https://ur.umbc.edu/poster-presentation-examples)

  c. PacBio Poster – [https://www.pacb.com/wp-content/uploads/PAG-Portik.pdf](https://www.pacb.com/wp-content/uploads/PAG-Portik.pdf)

3. Pick one poster and address the following points.

a. **Notice** – What about this poster most interests you?

b. **Wonder** – Two or three questions you would ask the authors.

c. **Support** – Two or three suggestions on how the poster could be improved.

4. Post your answers by replying to the “Project Work: Scientific Posters” topic in the Discussion Forum

### Grading Criteria

- <mark style="background-color: yellow">Submit URL to your reply on Canvas

### Footnotes

**Contributions and Affiliations**

- Valeriya Gaysinskaya, Johns Hopkins University
- Frederick Tan, Johns Hopkins University

Last Revised: February 2025

## Group Poster

### Introduction

An important part of scientific research is presenting your findings. This might be in the form of a peer-reviewed journal article or a more informal poster presentation at a conference or symposium. In this assignment, students will work with their groups to put together their work from the C-MOOR Labs into a Digital Poster.

### Part 1 - Choose a Template

1. Read through the [grading criteria] at the end of this document.
1. With your group, open a suggested [poster template] to use for your poster. 
1. Discuss with your group how you will divide up the work and exchange important information (e.g. phone numbers, email). Consider the following sections: 

- abstract, 
- introduction
- methods
- results
- discussion
- references 
- acknowledgments

### Part 2 - Make an Academic Research Poster

1. Complete the following components of your research poster with your group. You might not do them in this order, but these are the components you are being graded on. For more details on each of these sections and their role in a scientific paper, see the Scientific Literature Lab.

#### Title, Authors and Affiliations

Your poster should include: (1) a title for your work, (2) authors who contributed to the work and (3) author affiliations. Since you completed this work as a team of scientists, all of your team members are considered authors. List your team members in alphabetical order. The author’s affiliation is the university, college, research institution or company that the work was conducted at.  For us, the affiliation would be “Department of Biology, Clovis Community College, California, United States.”

#### Abstract

An abstract is a concise summary of your paper. An effective abstract will inform the reader of the scientific hypothesis being tested, the purpose, or “why”, of the study, the main methods, important results and conclusions in only **one paragraph**. When writing an abstract for a publication or presentation, there is always a maximum word or character count. For your poster, your abstract can have a **maximum length of 200 words**. Many scientists choose to write the abstract last.

Different fields of science have slightly different requirements and formats for abstracts. Here is a general guideline:

- Background: In one sentence, introduce your work. An effective introduction tells the reader what is known in the field (context) and identifies the gap of knowledge being addressed in the paper.
- Methods and Results: This section should be the longest part of your abstract, but no more than two or three sentences. This section is arguably the most important part of the abstract, because other scientists seek out a paper when they are interested in the results. The details for your methods will be contained in your paper, so in your abstract you can keep it brief. For your results, pick out the most important results and summarize them. Depending on your research, you may want to address the methods and results separately, but often they are intertwined (e.g. the example abstract below).
- Conclusions: In one sentence, concisely state what you learned from your research.

#### Introduction

A good introduction section should do two things. First, it provides context for your work by describing what is already known in the field, as well as an unknown that your research is addressing. The latter is often called the gap in knowledge. Second, it should identify your scientific question and hypothesis. Usually, the introduction starts broadly, describing the work of other scientists. It is important to summarize this work (do not quote) and to properly cite the work.

When writing your introduction, it is often helpful to start at the end. Identify your scientific question, your hypothesis and the gap of knowledge first. Then brainstorm what you will need to tell your readers in terms of context and background. For this project, be sure to include background information on Drosophila melanogaster and why it is a good model system for this research, because your audience might not know.

#### Materials and Methods

For your lab poster, your materials and methods section will detail your analysis of the data. Since this is a poster and not an article, you do not need to worry about including all the details and can keep it pretty brief. Don’t provide any of your results, just the methods. Because we did not make the RNA-seq libraries ourselves, you will simply cite the paper that made them instead of detailing their construction.  Scientists usually write this section of their paper first, followed by the results section. Some other things you might include would be what type of analysis you decided to do (type of plot, which parts of the midgut you analyzed, sets of genes,  what p-value you used, etc.).

#### Results

The Results section is where you will detail your data in the form of figures, tables and written text. Begin by creating your tables and figures. Place the figures and tables in order of how you want to present them and name them Figure 1, Figure 2, Table 1, Table 2, etc.

In your written narrative of the results, you should go through each figure in order, emphasizing any important results from each one. As you discuss each figure, you will reference the figure or table in parentheses. For example: “RT-PCR analysis shows an increase in gene expression for gene X (Fig 2).” It is important that you present your data clearly and in a logical manner.

Have fun playing around with how to organize your figures with the text to make the poster look professional. You need a minimum of 2 figures for your poster.

#### Discussion

The discussion section of the paper is your chance to analyze and interpret your results. For your lab report, make sure your discussion section includes all of the following:

1. What do your results mean?
1. How do they fit into the bigger picture?
1. If any experiments did not give expected results, hypothesize why that might have been the case and propose alternate experiments that could confirm or clarify your results.
1. Include at least one sentence of future work that you would do if you had more time or what students in upcoming semesters could do to continue to answer your questions.

#### References

All the references that you cite on your poster must be present in a References section.  For your lab report, make your reference section in alphabetical order by the first author’s last name. For your lab report, all of your sources will be scientific journals and should use the following format:

    Authors (year) “Title.” Journal Name, vol. #, page #s, DOI

Online article that is also in print:

    Haussecker D., Huang Y., Lau A., Parameswaran P., Fire A. Z. and M. A. Kay (2010) “Human tRNA-derived small RNAs in the global regulation of RNA silencing.” RNA, Vol. 16, page 637-695,  doi:10.1261/rna.2000810

Online article only:

    Marianes, A. and A. C. Spradling (2013) “Physiological and stem cell compartmentalization within the Drosophila midgut.” eLife, doi:10.7554/eLife.00886

#### In-text Citations

To save space on our posters, we will number our references 1 through 5 and use the numbers as citations throughout the text of your poster.

### Part 3 - Proofread and Add Final Touches

*Estimated time: 30 min to an hour*

1. Each group member should re-read the poster from beginning to end and fix any typos or grammatical errors.
1. Check the alignment of figures, text boxes, titles, etc.
1. Add some finishing touches. You can play with the color, the font, add additional images if it’s relevant.

### Part 4 - Canvas Discussion

*Estimated time: 30 min*

You will turn in your poster to be graded as a group in a Canvas Assignment and post it to a Canvas Discussion to be viewed by the class.

1. Convert your poster to a pdf.
1. Have one member of your group turn in the pdf of your poster to the Graded Canvas Assignment. This assignment is already set up so that if one group member turns it in, it will show as submitted for all students in the group. This is where your instructor will grade you poster as a group.
1. Have one member of your group post a pdf of your poster in the Canvas C-MOOR Poster Discussion.
    a. With your poster, introduce your  group members and copy and paste your abstract into the post.
    a. Insert your pdf into the post and edit the link so that it automatically shows the inline preview. This will make it easier for students to view your poster.
1. As an individual, read through the other posters from different groups.
1. Post comments

### Grading Criteria

Everyone in the group earns the same grade, so it is important to work together.

| Points | Category |
|:-|:-|
| 2 points | Title, Authors and Affiliations |
| 3 points | Abstract |
| 4 points | Introduction <br> 2 - relevant background <br> 2 - drosophila as a model system |
| 5 points | Methods |
| 5 points | Results |
| 4 points | Discussion |
| 5 points | References ( 2 primary sources, 5 sources total) |
| 2 points | Poster Organization  |

### Footnotes

#### Resources

- [Google Doc]

#### Contributions and Affiliations

- Stephanie R. Coffman, Clovis Community College
- Valeriya Gaysinskaya, Johns Hopkins University
- Frederick Tan, Johns Hopkins University

Last Revised:

## Poster Template

## Activity: Scientific Communication

# Next Steps

## Lecture: Next Steps

## Activity: Next Steos















