```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

# (PART\*) TUTORIALS {-}

# Galaxy Tutorials

## A short introduction to Galaxy

### Introduction

Galaxy [galaxyproject.org](galaxyproject.org) is a free, open-source system for analyzing data, authoring workflows, training and education, publishing tools, managing infrastructure, and more.  Among the notable features:

- [Graphical user interface](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101/tutorial.html) (GUI) for interactively running tools
- [Toolshed](https://toolshed.g2.bx.psu.edu/) with 10,000 tools ready to run
- Full featured [workflow](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/workflow-editor/tutorial.html) functionality
- Terabytes of the latest, curated [reference data](https://galaxyproject.org/admin/reference-data-repo)
- Extensive training [tutorials](https://training.galaxyproject.org/) and infrastructure
- Large international [community](https://galaxyproject.org/community) of users and developers

### Activity

*Estimated time: 40 min*

#### Instructions

1. Review slides for “A short introduction to Galaxy”
- [training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-short/slides.html](training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-short/slides.html)
2. Complete the hands-on tutorial
- [training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-short/tutorial.html](training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-short/tutorial.html)

### Grading Criteria

- Submit URL to your shared Galaxy history on Canvas

### Footnotes

**Resources**

- Introduction to Galaxy Analyses [topic](https://training.galaxyproject.org/training-material/topics/introduction/)

**Contributions and Affiliations**

- Frederick Tan, Johns Hopkins University

Last Revised: January 2025


## QC and Galaxy Workflows

### Introduction

In the “A short introduction to Galaxy” activity you learned how to upload a file, use a tool, view results, view histories, extract and run a workflow, and share a history.  You will now practice using these skills to do one of the first things when encountering a new sequencing dataset – quality control (QC).  After assessing the quality of both short and long reads, gain more practice with workflows by creating and editing a new workflow.

### Activity 1 – Quality Control (QC)

*Estimated time: 90 min*

#### Instructions

1. Complete the “Quality Control” hands-on tutorial: [training.galaxyproject.org/training-material/topics/sequence-analysis/tutorials/quality-control/tutorial](https://training.galaxyproject.org/training-material/topics/sequence-analysis/tutorials/quality-control/tutorial.html)

- **NOTE**: Do all hands-on steps in a single Galaxy history

### Activity 2 – Creating, Editing and Importing Galaxy Workflows

*Estimated time: 30 min*

#### Instructions

1. Complete the “Creating, Editing and Importing Galaxy Workflows” hands-on tutorial: [training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/workflow-editor/tutorial](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/workflow-editor/tutorial.html)

### Grading Criteria

- <mark style="background-color: yellow">Submit URL to your shared Galaxy “Quality Control” history on Canvas

### Footnotes

**Resources**

- Using Galaxy and Managing your Data [topic](https://training.galaxyproject.org/training-material/topics/galaxy-interface/)
- Introduction to Galaxy and Sequence analysis [pathway](https://training.galaxyproject.org/training-material/learning-pathways/intro-to-galaxy-and-genomics.html)

**Contributions and Affiliations**

- Frederick Tan, Johns Hopkins University

Last Revised: February 2025


## Galaxy data collections

### Introduction

Collections in Galaxy can be useful when you have to deal with large numbers of datasets.  Examples of when you might use collections include when you have many DNA sequencing samples (e.g. .fastq files) or when you have many genome assembly contigs (e.g. .fasta files).  Dataset collections allow you to not only organize these datasets but they also allow you to manipulate them in a single batch operation.

### Activity

*Estimated time: 45 min*

#### Instructions

1. Review the “Datasets versus collections” FAQ

- [training.galaxyproject.org/training-material/faqs/galaxy/histories_datasets_vs_collections.html](http://training.galaxyproject.org/training-material/faqs/galaxy/histories_datasets_vs_collections.html)

2. Complete the “Using dataset collections” hands-on tutorial

- [training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/collections/tutorial.html](http://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/collections/tutorial.html)

### Grading Criteria

- <mark style="background color: yellow">Submit URL to your shared Galaxy history on Canvas

### Footnotes

**Resources**

- Using Galaxy and Managing your Data [topic]

**Contributions and Affiliations**

- Frederick Tan, Johns Hopkins University

Last Revised: January 2025
