# Instructor Guide {-}

C-MOOR Microbial Mysteries CURE content overview.


## Course Content

The Microbial Mysteries course content was organized and presented by way of Unit modules below. Each unit has a main theme, reflected by the unit title. Practically, each unit is a week covering both, themed assignments and those from previous and next units, including any other additional material an instructor wishes to cover. 

  - Each class lasted 1 hour and 15 minutes
  - Core units 1, 2, 3 and 4, over the coure of 4 weeks and 8 classes (1 unit per week and 2 classes/week) was typically associated with 1.5-2 hrs of homework per class, or 3-4 hours of homework per week. 

<br>

Course content was organized broadly into 3 categories:

1. Structured (Core) Units - on weekly basis, Units 0 through 4
2. Research Module - over the course of 7 weeks
3. Professional Development Module - over the course of 4 weeks

### Structured Units 

- **Week 1** - Introduction: 1 class a week

| Unit 0: Introduction | Type| Length | Spring 2025 JHU Due Data |
|:--|:--|:--|:--|
| Lecture: Welcome to Your Genomics Adventure!| in-class| 20 min | Jan 21 |
| Create Accounts| Homework | 30 min | Jan 21 |
| Lecture: The Scientific Process| in-class| 20 min | Jan 22 |
| Post Introcuctions | Homework| 30 min | Jan 22 | 

- **Week 2** - Scientific Literature: 2 classes a week

| Unit 1-session 1 | Type| Length |Spring 2025 JHU Due Data |
|:--|:--|:--|:--|
| Lecture: What's in your XYZ? | in-class| 20 min | Jan 23 |
| Activity: Taxonomy Profiling Spreadsheet| Homework | 45 min |  Jan 23 |
| Galaxy Tutorial: A short introduction to Galaxy| Homework| 40 min |  Jan 23 |
| Pre-lab: Scientific Literature | Homework| 45 min |Jan 27 |
| <br>|
| **Unit 1-session 2** | Type| Length | Spring 2025 JHU Due Data |
|:--|:--|:--|:--|
|Discussion: Scientific Literature | in-class| 30 min | Jan 27 |
|Lecture: Scientific Literature| in-class| 20 min | Jan 28 |
|Activity: Scientific Literature| Homework| 80 min | Jan 29 |
|Presentation: Scientific Literature | in-class| 30 min | Jan 30|

- **Week 3** - 2 classes a week

| Unit 2: Microbial Genomes | Type| 
|:--|:--|
| Lecture: Microbial Genomes | in-class|
| Pre-lab: Microbial Genomes| Homework |
| Galaxy Tutorial: QC & Galaxy Workflows | Homework|
| Discussion: Microbial Genomes | in-class|
|Project: Microbial Genomes| Homework|
|SciServer Tutorial: test-drive R | Homework|
|Presentation: Microbial Genomes | in-class|

- **Week 4** - 2 classes a week

| Unit 3: Taxonomy Profiling | Type| 
|:--|:--|
| Lecture: Taxonomy Profiling | in-class|
| Pre-lab: Taxonomy Profiling| Homework |
| Lecture: Possible Datasets| in-class|
| Activity: Possible Datasets | in-class|
| Galaxy Tutorial: Using dataset collections | Homework|
| Discussion: Taxonomy Profiling | in-class|
| Project: Taxonomy Profiling | Homework|
| SciServer Tutorial: Meet R! Homework|
| Presentation: Taxonomy Profiling Project| Homework |

- **Week 5** - 2 classes a week

| Unit 4: Finding AMRs | Type| 
|:--|:--|
| Lecture: Finding AMRs | in-class|
| Pre-lab: Finding AMRs | Homework|
| Lecture: Scientific Posters | in-class|
| Activity: Scientific Posters | Homework|
| SciServer Tutorial: R for Data Science 1 | Homework|
| Discussion: Finding AMRs | in-class|
| Project: Finding AMRs | Homework|
| SciServer Tutorial: R for Data Science 2 | Homework|
| Presentation: Finding AMRs | in-class|

- **Week 6** - 2 classes a week

| Unit 5: Kickstart Project Work | Type| 
|:--|:--|
| Lecture: Kickstart Project Work | in-class|
| Activity: Kickstart Project Work | Homework |
| Round Table Data - slidedeck| in class |
| Round Table Troubleshooting - slidedeck | in class |

### Research Module 

- **Weeks 7-13** - 2 classes a week

| Module: Project Work | Type|
|:--|:--|
| Project Work Organizer | Written Doc|
| Written Check-in #1 | Written Doc|
| Written Check-in # 2| Written Doc (Poster)|
| Advisory Meeting # 1| Written Doc (Poster)|
| Written Check-in # 3| Written Doc|
| Peer-review # 1| Written Doc|
| Advisory Meeting # 2| Written Doc (Poster)|
| Written Check-in # 4| Written Doc|
| Peer-review # 2| Written Doc|
| Final Presentation | Poster Session|
<br>

Instructor and Students are encouraged to use this organizer to find instructions and track documents.

- For setting up meeting times, we recommend using [when2meet](https://www.when2meet.com)

|Group | Check-in | Poster | Meeting #1 | Meeting # 2|
|:--| :--| :-- | :-- | :-- | 
|Group A| Doc | Slides | Date 1 | Date 2| 
|Group B| Doc | Slides | Date 1 | Date 2| 
|Group C| Doc | Slides | Date 1 | Date 2| 
|Group D| Doc | Slides | Date 1 | Date 2| 

### Professional Development Module

- **Weeks 9-13** 

| Module: Project Work | Type|
|:--|:--|
| Activity: Science Talks | Homework|
| Science Talks | Guest Lecture|
| Activity: Science Talks | Homework|
| Science Talks | Guest Lecture|
| Activity: Scientific Communication | Homework|
| Activity: Next Steps | Homework|

## Core Competencies

The activities in this CURE address several core concepts and competencies as identified by professional societies and working groups.  The table below lists the relevant core concepts and competencies adopted from the following sources:

  - [Scientific Thinking and Critical Thinking in Science Education](https://doi.org/10.1007/s11191-023-00460-5)
  - [Genetics Learning Framework](https://genetics-gsa.org/education/genetics-learning-framework/) by [GSA](https://genetics-gsa.org/)
  - [Bioinformatics core competencies for undergraduate life sciences education](https://doi.org/10.1371/journal.pone.0196878) by [NIBLSE](https://qubeshub.org/community/groups/niblse)
- [Establishing a baseline of science communication skills in an undergraduate environmental science course](https://stemeducationjournal.springeropen.com/articles/10.1186/s40594-021-00304-0)


|**Critical Thinking**|
| :--|
| - Enhancing higher-order cognitive skills that go beyond memorization|
| - Solve problems using quantitative and qualitative information and analysis|
| - Promote scientific evidence-based thinking and active learning|
|<br>| 
|**Genetics**|
| - Locate, read, and comprehend primary literature research papers on genetics topics|
| - Implement observational strategies to formulate a question|
| - Generate testable hypotheses|
| - Generate and interpret graphs displaying experimental results|
| - Critique data and datasets and use bioinformatics to assess genetics data|
| <br>|
|**Bioinformatics**|
| - Explain the role of computation in addressing hypothesis-driven and hypothesis-generating questions within the life sciences|
| - Develop bioinformatics core competencies for undergraduate life sciences education| 
| - Use bioinformatics tools to examine complex biological problems in genetics, evolution, information flow, and other important areas of biology|
| - Find, retrieve, and organize various types of biological data |
| use bioinformatics tools to analyze genomic and/or metagenomic data | 
| - Explore and/or model biological interactions and networks a using bioinformatics|
| <br>|
|**Scientific Communication**|
| - Communicate experimental results effectively, including written summaries, verbal presentations and poster presentation|
| - Understand Essential Elements for Effective Science Communication (EEES) such as Who? (is the audience), Why? (e.g. Purpose), What? (content) and How? (e.g. style).
| <br>|

## What to know

As an instructor, 

- What do I have to know to teach this course?
- What level do I need to be at?
- I am not a genomics expert, can I do it?
- I don't know coding, can I do it?

## Where to get help

- Ask C-MOOR community for help [https://help.c-moor.org]

As an instructor, where can I get help in teaching this course?
