```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

# SciServer Tutorials

## Meet R!

### Introduction

R is a popular programming language for statistical computing and data visualization [wikipedia](https://wikipedia.org/wiki/R_(programming_language).  Notable features include the [RStudio IDE](https://posit.co/products/open-source/rstudio) built to help you be more productive with R (and Python); the [tidyverse](https://tidyverse.org/packages) collection of packages that aims to make data science faster, easier, and more fun; and importantly the [Bioconductor](https://bioconductor.org) project with its active support community and robust genomics tooling.  Now that you completed “test-driveR” and got a taste of analyzing a real world genomics dataset using R it’s time to learn more about how R stores and operates on data using concepts such as variables, vectors, and data.frames.

### Activity

*Estimated time: 25 min*

#### Instructions

1. Resume your C-MOOR LearnR container

  a. Open sciserver.org in a web browser and log in to your account.

  b. Click “Home” in the top menu to return to the home page.

  c. Scroll down to the second set of boxes and click “Compute”.

  d. Resume your C-MOOR LearnR container by clicking on its name.

2. Complete your next LearnR tutorial

  a. Click on “Meet R!”. The tutorial will open in a new tab.

  b. Complete the tutorial and answer the questions below.

#### Questions

|1. Variables – Define what is a variable, give a line of R code that stores information in a variable, and explain how one would view the data stored in a variable.|
|:--|
| Define variable:|
| Code:|
| Explain:|
<br>

|2. Vectors – Provide two lines of R code, one which stores a vector of numbers in a variable, and one which performs a mathematical operation on each element of that variable (e.g. multiplication). |
|:--|
|Code 1:|
|Code 2:|
<br>

|3. Plotting – Copy and paste as text your code from the final code block in the tutorial.  Also insert a screenshot of your resulting plot.|
|:--|
|Code text:|
|Plot screenshot:|
<br>

### Grading Criteria

- <mark style="background color: yellow">Download as Microsoft Word (.docx) and upload on Canvas

### Footnotes

**Resources**

- Google Doc
- [R cheat sheet](https://github.com/C-MOOR/cure-rnaseq/blob/master/tutorials/Rcheatsheet.md)

**Contributions and Affiliations**

- Katherine Cox, Johns Hopkins University
- Frederick Tan, Johns Hopkins University

Last Revised: February 2025


