```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```
# (PART\*) Testing Ideas {-}

# Taxonomy Profiling

## Lecture: Taxonomy Profiling

```{r, echo=FALSE, fig.alt=''}
ottrpal::include_slide("https://docs.google.com/presentation/d/10P4ktKWSrRpM1YAWYW31tLly_jf1rcfgCMbzZ9Tx9xY/edit?slide=id.g35f391192_00#slide=id.g35f391192_00")
```

[Slides: Taxonomy Profiling](https://docs.google.com/presentation/d/10P4ktKWSrRpM1YAWYW31tLly_jf1rcfgCMbzZ9Tx9xY/edit?usp=sharing)


## Homework: Taxonomy Profiling Prelab


## Lecture: Possible Datasets

```{r, echo=FALSE, fig.alt=''}
ottrpal::include_slide("https://docs.google.com/presentation/d/1VxwSmAY8BUs3EfVcxPm3I8kNYJWjVqoHJrGOX3X3sog/edit?slide=id.g35f391192_00#slide=id.g35f391192_00")
```

[Slides: Possible Datasets](https://docs.google.com/presentation/d/1VxwSmAY8BUs3EfVcxPm3I8kNYJWjVqoHJrGOX3X3sog/edit?usp=sharing)


## Homework: Possible Datasets Activity


## Homework: Using dataset collections


## Discussion: Taxonomy Profiling Prelab


## Homework: Taxonomy Profiling Project

## Activity: Meet R!

## Presentation: Taxonomy Profiling Project

